#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://rm-bp1nnjhvq3tra324d.mysql.rds.aliyuncs.com:3306/mini_app_db?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=GMT%2B8
#    username: root
#    password: v7#ROHq7JmKD
spring:
  cloud:
    gateway:
      routes:
        - id: custom_add_request_header_route
          uri: http://localhost:9091
          predicates:
            - Host=localhost:9090

